import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Github, Chrome } from "lucide-react"

export function HeroSection() {
  return (
    <section className="relative overflow-hidden border-b border-border">
      <div className="bg-grid-pattern absolute inset-0 opacity-60" />
      <div className="relative mx-auto max-w-6xl px-6 py-24 md:py-32">
        <div className="flex flex-col items-center text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-muted px-3 py-1">
            <span className="text-xs text-primary">New</span>
            <span className="text-xs text-muted-foreground">Now with multi-language support</span>
          </div>
          <h1 className="max-w-3xl text-balance text-4xl font-bold tracking-tighter text-foreground md:text-5xl lg:text-6xl">
            Auto-generate PR descriptions with AI
          </h1>
          <p className="mt-6 max-w-2xl text-pretty text-base text-muted-foreground md:text-lg">
            Stop writing PR descriptions manually. Laplace analyzes your diff and generates clear, consistent
            descriptions in seconds. Available for Chrome and Edge.
          </p>
          <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row">
            <Button asChild size="lg" className="gap-2 bg-primary text-primary-foreground hover:bg-primary/90">
              <Link href="#install">
                <Chrome className="h-4 w-4" />
                Install Extension
              </Link>
            </Button>
            <Button
              asChild
              variant="outline"
              size="lg"
              className="gap-2 border-border bg-transparent text-foreground hover:bg-muted"
            >
              <Link href="https://github.com" target="_blank" rel="noopener noreferrer">
                <Github className="h-4 w-4" />
                View on GitHub
              </Link>
            </Button>
          </div>
        </div>

        {/* Browser Mockup */}
        <div className="mt-16 md:mt-20">
          <div className="mx-auto max-w-4xl overflow-hidden rounded-sm border border-border bg-card">
            {/* Browser Chrome */}
            <div className="flex items-center gap-2 border-b border-border bg-muted px-4 py-3">
              <div className="flex gap-1.5">
                <div className="h-2.5 w-2.5 rounded-full bg-[#ff5f57]" />
                <div className="h-2.5 w-2.5 rounded-full bg-[#febc2e]" />
                <div className="h-2.5 w-2.5 rounded-full bg-[#28c840]" />
              </div>
              <div className="ml-4 flex-1">
                <div className="mx-auto max-w-md rounded-sm bg-background px-3 py-1 text-xs text-muted-foreground">
                  github.com/acme/project/pull/42
                </div>
              </div>
            </div>
            {/* PR Interface */}
            <div className="p-6">
              <div className="mb-4 flex items-center gap-3">
                <div className="rounded-sm bg-primary/20 px-2 py-0.5 text-xs text-primary">Open</div>
                <span className="text-sm text-foreground">feat: Add user authentication flow</span>
              </div>
              <div className="rounded-sm border border-border bg-muted p-4">
                <div className="mb-3 flex items-center gap-2 text-xs text-muted-foreground">
                  <div className="h-4 w-4 rounded-full bg-primary/30" />
                  <span>Generated by Laplace</span>
                </div>
                <div className="space-y-2 text-sm text-foreground">
                  <p className="font-medium">Summary</p>
                  <p className="text-muted-foreground">
                    This PR implements user authentication including login, logout, and session management. It adds
                    protected routes and integrates with the existing user service.
                  </p>
                  <p className="mt-4 font-medium">Changes</p>
                  <ul className="list-inside list-disc space-y-1 text-muted-foreground">
                    <li>Added AuthContext for global auth state</li>
                    <li>Implemented login/logout API routes</li>
                    <li>Created ProtectedRoute wrapper component</li>
                    <li>Updated navigation with user menu</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
